import { ExcelRow } from '../types';

/**
 * Data Dummy Resmi Representasi File "laporan_renja (87).xlsx"
 * Kementerian Perindustrian Republik Indonesia
 * Fokus: Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI - 019.07),
 * Sekretariat Jenderal (019.01), Ditjen Agro (019.02), Ditjen KPAII (019.06), dll.
 */
export const SAMPLE_EXCEL_DATA: ExcelRow[] = [
  // =========================================================================
  // 1. BSKJI (019.07) - BELANJA PEGAWAI (RM) & OPERASIONAL PERKANTORAN (RM/PNBP/BLU)
  // =========================================================================
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Sekretariat BSKJI',
    satker: 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri',
    type_komponen: 'Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Dukungan Manajemen',
    kegiatan: 'Layanan Dukungan Operasional Satker',
    kro: 'KRO.004 Layanan Perkantoran',
    ro: 'RO.05 Gaji dan Tunjangan',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Selatan',
    'lokasi ro': 'Kantor Pusat Kemenperin',
    komponen: '001-Gaji dan tunjangan',
    alokasi_komponen_0: 18450000000,
    target_komponen_0: 12,
    satuan: 'Bulan Layanan',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.WA.2157.EBA.994.001'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Sekretariat BSKJI',
    satker: 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri',
    type_komponen: 'Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Dukungan Manajemen',
    kegiatan: 'Layanan Dukungan Operasional Satker',
    kro: 'KRO.004 Layanan Perkantoran',
    ro: 'RO.06 Operasional Satker',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Selatan',
    'lokasi ro': 'Kantor Pusat Kemenperin',
    komponen: '002-operasional dan pemeliharaan kantor',
    alokasi_komponen_0: 8750000000,
    target_komponen_0: 12,
    satuan: 'Bulan Layanan',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.WA.2157.EBA.994.002'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Sekretariat BSKJI',
    satker: 'Sekretariat Badan Standardisasi dan Kebijakan Jasa Industri',
    type_komponen: 'Operasional',
    sumber_dana: 'PNBP',
    program: 'Program Dukungan Manajemen',
    kegiatan: 'Layanan Dukungan Operasional Satker',
    kro: 'KRO.004 Layanan Perkantoran',
    ro: 'RO.06 Operasional Satker',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Selatan',
    'lokasi ro': 'Kantor Pusat Kemenperin',
    komponen: '002-operasional dan pemeliharaan kantor',
    alokasi_komponen_0: 1200000000,
    target_komponen_0: 12,
    satuan: 'Bulan Layanan',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.WA.2157.EBA.994.002'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Balai Besar Standardisasi dan Pelayanan Jasa Industri Agro (BBSPJIA Bogor)',
    satker: 'BBSPJIA Bogor',
    type_komponen: 'Operasional',
    sumber_dana: 'BLU',
    program: 'Program Dukungan Manajemen',
    kegiatan: 'Layanan Dukungan Operasional Satker',
    kro: 'KRO.004 Layanan Perkantoran',
    ro: 'RO.06 Operasional Satker',
    propinsi: 'Jawa Barat',
    kabupaten: 'Kota Bogor',
    'lokasi ro': 'BBSPJIA Bogor',
    komponen: '002-operasional dan pemeliharaan kantor',
    alokasi_komponen_0: 3450000000,
    target_komponen_0: 12,
    satuan: 'Bulan Layanan',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.WA.2157.EBA.994.002'
  },

  // =========================================================================
  // 2. BSKJI (019.07) - PROGRAM RISET, INOVASI, DAN STANDARISASI INDUSTRI (019.07.BD)
  // =========================================================================
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Industri Hijau',
    satker: 'Pusat Industri Hijau',
    type_komponen: 'Non Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Pengembangan Standar Industri Hijau',
    kro: 'KRO.002 Fasilitasi Industri Hijau',
    ro: 'RO.02 Verifikasi Industri Hijau',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Pusat',
    'lokasi ro': 'Kantor Pusat Kemenperin',
    komponen: '051 Honorarium Tim Teknis Evaluasi Industri Hijau',
    alokasi_komponen_0: 485000000,
    target_komponen_0: 24,
    satuan: 'Laporan Evaluasi',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2155.BMA.002.051'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Industri Hijau',
    satker: 'Pusat Industri Hijau',
    type_komponen: 'Non Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Pengembangan Standar Industri Hijau',
    kro: 'KRO.002 Fasilitasi Industri Hijau',
    ro: 'RO.04 Audit Energi Pabrik',
    propinsi: 'Jawa Barat',
    kabupaten: 'Kab. Bogor',
    'lokasi ro': 'BBSPJIA Bogor',
    komponen: '052 Perjalanan Dinas Pendampingan Audit Energi',
    alokasi_komponen_0: 620000000,
    target_komponen_0: 35,
    satuan: 'Pabrik Industri',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2155.BMA.004.052'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Industri Hijau',
    satker: 'BBSPJI Surabaya',
    type_komponen: 'Non Operasional',
    sumber_dana: 'PNBP',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Pengembangan Standar Industri Hijau',
    kro: 'KRO.002 Fasilitasi Industri Hijau',
    ro: 'RO.04 Audit Energi Pabrik',
    propinsi: 'Jawa Timur',
    kabupaten: 'Kota Surabaya',
    'lokasi ro': 'BBSPJI Surabaya',
    komponen: '053 Pengadaan Bahan & Uji Emisi Karbon Sektor Kimia',
    alokasi_komponen_0: 950000000,
    target_komponen_0: 60,
    satuan: 'Sampel Uji Emisi',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2155.BMA.004.053'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Standardisasi Industri',
    satker: 'Pusat Standardisasi Industri',
    type_komponen: 'Non Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Penyusunan dan Harmonisasi Standar Industri (RSNI)',
    kro: 'KRO.001 Pembinaan Standar Industri',
    ro: 'RO.01 Perumusan SNI Baru',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Selatan',
    'lokasi ro': 'Balai Standardisasi Jakarta',
    komponen: '054 Konsinyering Penyusunan Dokumen RSNI Tahap 1-3',
    alokasi_komponen_0: 1250000000,
    target_komponen_0: 15,
    satuan: 'Dokumen RSNI',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2155.BMA.001.054'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Standardisasi Industri',
    satker: 'BBSPJPPI Semarang',
    type_komponen: 'Non Operasional',
    sumber_dana: 'PNBP',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Pengujian Mutu dan Sertifikasi Produk',
    kro: 'KRO.003 Pengawasan Standardisasi',
    ro: 'RO.03 Sertifikasi ISO 17025',
    propinsi: 'Jawa Tengah',
    kabupaten: 'Kota Semarang',
    'lokasi ro': 'BBSPJPPI Semarang',
    komponen: '055 Pemeliharaan dan Kalibrasi Instrumen Pengujian Mutu Lingkungan',
    alokasi_komponen_0: 1850000000,
    target_komponen_0: 25,
    satuan: 'Unit Instrumen Lab',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2155.BMA.003.055'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Standardisasi Industri',
    satker: 'BBSPJI Medan',
    type_komponen: 'Non Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Pengujian Mutu dan Sertifikasi Produk',
    kro: 'KRO.003 Pengawasan Standardisasi',
    ro: 'RO.03 Sertifikasi ISO 17025',
    propinsi: 'Sumatera Utara',
    kabupaten: 'Kota Medan',
    'lokasi ro': 'BBSPJI Medan',
    komponen: '056 Workshop Akreditasi Lembaga Sertifikasi & Lab Penguji',
    alokasi_komponen_0: 420000000,
    target_komponen_0: 60,
    satuan: 'Peserta / Auditor',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2155.BMA.003.056'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Optimalisasi Pemanfaatan Teknologi Industri',
    satker: 'BBSPJILM Bandung',
    type_komponen: 'Non Operasional',
    sumber_dana: 'SBSN',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Optimalisasi Pemanfaatan Teknologi Industri & Mesin Logam',
    kro: 'KRO.001 Pembinaan Standar Industri',
    ro: 'RO.01 Perumusan SNI Baru',
    propinsi: 'Jawa Barat',
    kabupaten: 'Kota Bandung',
    'lokasi ro': 'BBSPJILM Bandung',
    komponen: '057 Uji Coba Purwarupa Mesin CNC Pengolah Logam Ringan',
    alokasi_komponen_0: 1650000000,
    target_komponen_0: 5,
    satuan: 'Prototipe Mesin',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2156.BMA.001.057'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Optimalisasi Pemanfaatan Teknologi Industri',
    satker: 'BBSPJI Makassar',
    type_komponen: 'Non Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Optimalisasi Pemanfaatan Teknologi Industri',
    kro: 'KRO.002 Fasilitasi Industri Hijau',
    ro: 'RO.02 Verifikasi Industri Hijau',
    propinsi: 'Sulawesi Selatan',
    kabupaten: 'Kota Makassar',
    'lokasi ro': 'BBSPJI Makassar',
    komponen: '058 Diseminasi Teknologi Daur Ulang Limbah Pengolahan Kakao & Kopi',
    alokasi_komponen_0: 380000000,
    target_komponen_0: 80,
    satuan: 'IKM Binaan',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2156.BMA.002.058'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Standardisasi Industri',
    satker: 'BBSPJPPI Semarang',
    type_komponen: 'Non Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Pengujian Mutu dan Pengawasan Standar Produk',
    kro: 'KRO.003 Pengawasan Standardisasi',
    ro: 'RO.01 Perumusan SNI Baru',
    propinsi: 'Jawa Tengah',
    kabupaten: 'Kota Surakarta',
    'lokasi ro': 'BBSPJPPI Semarang',
    komponen: '061 Uji Petik Produk Bertanda SNI Wajib di Pasar Domestik',
    alokasi_komponen_0: 520000000,
    target_komponen_0: 150,
    satuan: 'Sampel Uji Pasar',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2155.BMA.001.061'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Standardisasi Industri',
    satker: 'BBSPJIKFK Jakarta',
    type_komponen: 'Non Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Pengembangan Standar Industri Bahan Kimia & Kemasan',
    kro: 'KRO.001 Pembinaan Standar Industri',
    ro: 'RO.01 Perumusan SNI Baru',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Timur',
    'lokasi ro': 'BBSPJIKFK Jakarta',
    komponen: '064 Penyusunan Pedoman Spesifikasi Teknis Komponen Baterai EV & Kemasan Ramah Lingkungan',
    alokasi_komponen_0: 740000000,
    target_komponen_0: 4,
    satuan: 'Dokumen NSPK',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2155.BMA.001.064'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Standardisasi Industri',
    satker: 'BBSPJI Makassar',
    type_komponen: 'Non Operasional',
    sumber_dana: 'PNBP',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Pengujian Mutu dan Sertifikasi Produk Hasil Bumi',
    kro: 'KRO.003 Pengawasan Standardisasi',
    ro: 'RO.03 Sertifikasi ISO 17025',
    propinsi: 'Sulawesi Selatan',
    kabupaten: 'Kota Makassar',
    'lokasi ro': 'BBSPJI Makassar',
    komponen: '066 Audit Surveillance Laboratorium Uji Pangan & Hasil Bumi Terakreditasi',
    alokasi_komponen_0: 360000000,
    target_komponen_0: 24,
    satuan: 'Lembaga Penilai',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2155.BMA.003.066'
  },

  // =========================================================================
  // 3. BSKJI (019.07) - PROGRAM PENINGKATAN NILAI TAMBAH DAN DAYA SAING INDUSTRI (019.07.EC)
  // =========================================================================
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Pusat Optimalisasi Pemanfaatan Teknologi Industri',
    satker: 'Pusat Optimalisasi Pemanfaatan Teknologi Industri',
    type_komponen: 'Non Operasional',
    sumber_dana: 'PNBP',
    program: 'Program Nilai Tambah dan Daya Saing Industri',
    kegiatan: 'Optimalisasi Pemanfaatan Teknologi Industri 4.0',
    kro: 'KRO.001 Pembinaan Standar Industri',
    ro: 'RO.02 Verifikasi Industri Hijau',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Pusat',
    'lokasi ro': 'Kantor Pusat Kemenperin',
    komponen: '062 Forum Temu Bisnis & FGD Transformasi Indonesia Industry 4.0 (INDI 4.0)',
    alokasi_komponen_0: 680000000,
    target_komponen_0: 10,
    satuan: 'Kegiatan Temu Bisnis',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.EC.2158.BMA.002.062'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Sekretariat BSKJI',
    satker: 'BBSPJI Surabaya',
    type_komponen: 'Non Operasional',
    sumber_dana: 'PNBP',
    program: 'Program Nilai Tambah dan Daya Saing Industri',
    kegiatan: 'Layanan Pengujian dan Sertifikasi Industri Manufaktur',
    kro: 'KRO.004 Layanan Perkantoran',
    ro: 'RO.03 Sertifikasi ISO 17025',
    propinsi: 'Jawa Timur',
    kabupaten: 'Kota Surabaya',
    'lokasi ro': 'BBSPJI Surabaya',
    komponen: '065 Pembaruan Lisensi Software Simulasi Karakteristik Material Uji Mutu',
    alokasi_komponen_0: 1250000000,
    target_komponen_0: 15,
    satuan: 'Lisensi User',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.EC.2157.BMA.003.065'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Sekretariat BSKJI',
    satker: 'BBSPJI Samarinda',
    type_komponen: 'Non Operasional',
    sumber_dana: 'SBSN',
    program: 'Program Nilai Tambah dan Daya Saing Industri',
    kegiatan: 'Peningkatan Sarana & Prasarana Balai Standardisasi',
    kro: 'KRO.004 Layanan Perkantoran',
    ro: 'RO.03 Sertifikasi ISO 17025',
    propinsi: 'Kalimantan Timur',
    kabupaten: 'Kota Samarinda',
    'lokasi ro': 'BBSPJI Samarinda',
    komponen: '059 Renovasi dan Modernisasi Laboratorium Mikrobiologi & Lingkungan',
    alokasi_komponen_0: 2450000000,
    target_komponen_0: 1,
    satuan: 'Gedung Laboratorium',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.EC.2157.BMA.003.059'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Balai Standardisasi dan Pelayanan Jasa Industri (BSPJI) Banda Aceh',
    satker: 'BSPJI Banda Aceh',
    type_komponen: 'Non Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Pendampingan Standardisasi dan Sertifikasi Halal Industri Minyak Atsiri',
    kro: 'KRO.002 Fasilitasi Industri Hijau',
    ro: 'RO.01 Perumusan SNI Baru',
    propinsi: 'Aceh',
    kabupaten: 'Kota Banda Aceh',
    'lokasi ro': 'BSPJI Banda Aceh',
    komponen: '067 Fasilitasi Sertifikasi Halal & SNI Nilam Aceh',
    alokasi_komponen_0: 310000000,
    target_komponen_0: 25,
    satuan: 'IKM Nilam',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2155.BMA.001.067'
  },
  {
    'unit eselon1': 'Badan Standardisasi dan Kebijakan Jasa Industri (BSKJI)',
    'unit eselon2': 'Balai Standardisasi dan Pelayanan Jasa Industri (BSPJI) Banjarbaru',
    satker: 'BSPJI Banjarbaru',
    type_komponen: 'Non Operasional',
    sumber_dana: 'BLU',
    program: 'Program Riset, Inovasi, dan Standarisasi Industri',
    kegiatan: 'Layanan Pengujian Kualitas Air dan Udara Industri Tambang',
    kro: 'KRO.003 Pengawasan Standardisasi',
    ro: 'RO.03 Sertifikasi ISO 17025',
    propinsi: 'Kalimantan Selatan',
    kabupaten: 'Kota Banjarbaru',
    'lokasi ro': 'BSPJI Banjarbaru',
    komponen: '068 Pengadaan Reagen dan Bahan Uji Baku Mutu Air Limbah',
    alokasi_komponen_0: 580000000,
    target_komponen_0: 120,
    satuan: 'Paket Reagen Uji',
    tahun_anggaran: '2026',
    kode_anggaran: '019.07.BD.2155.BMA.003.068'
  },

  // =========================================================================
  // 4. SEKRETARIAT JENDERAL (019.01)
  // =========================================================================
  {
    'unit eselon1': 'Sekretariat Jenderal',
    'unit eselon2': 'Biro Keuangan dan BMN',
    satker: 'Sekretariat Jenderal Kemenperin',
    type_komponen: 'Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Dukungan Manajemen',
    kegiatan: 'Pengelolaan Keuangan, Perencanaan, dan Dukungan Teknis',
    kro: 'KRO.004 Layanan Perkantoran',
    ro: 'RO.05 Gaji dan Tunjangan',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Selatan',
    'lokasi ro': 'Kantor Pusat Kemenperin',
    komponen: '001-Gaji dan tunjangan',
    alokasi_komponen_0: 32600000000,
    target_komponen_0: 12,
    satuan: 'Bulan Layanan',
    tahun_anggaran: '2026',
    kode_anggaran: '019.01.WA.2157.EBA.994.001'
  },
  {
    'unit eselon1': 'Sekretariat Jenderal',
    'unit eselon2': 'Biro Umum dan Pengadaan',
    satker: 'Sekretariat Jenderal Kemenperin',
    type_komponen: 'Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Dukungan Manajemen',
    kegiatan: 'Layanan Pemeliharaan Gedung & Utilitas Kantor Pusat',
    kro: 'KRO.004 Layanan Perkantoran',
    ro: 'RO.06 Operasional Satker',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Selatan',
    'lokasi ro': 'Kantor Pusat Kemenperin',
    komponen: '002-operasional dan pemeliharaan kantor',
    alokasi_komponen_0: 14200000000,
    target_komponen_0: 12,
    satuan: 'Bulan Layanan',
    tahun_anggaran: '2026',
    kode_anggaran: '019.01.WA.2157.EBA.994.002'
  },
  {
    'unit eselon1': 'Sekretariat Jenderal',
    'unit eselon2': 'Pusat Data dan Informasi (Pusdatin)',
    satker: 'Pusat Data dan Informasi',
    type_komponen: 'Non Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Dukungan Manajemen',
    kegiatan: 'Pengembangan Sistem Informasi Industri Nasional (SIINas)',
    kro: 'KRO.004 Layanan Perkantoran',
    ro: 'RO.03 Sertifikasi ISO 17025',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Selatan',
    'lokasi ro': 'Kantor Pusat Kemenperin',
    komponen: '069 Pemeliharaan Cloud Server dan Keamanan Siber SIINas',
    alokasi_komponen_0: 3800000000,
    target_komponen_0: 12,
    satuan: 'Bulan Monitoring',
    tahun_anggaran: '2026',
    kode_anggaran: '019.01.WA.2157.BMA.003.069'
  },

  // =========================================================================
  // 5. DITJEN INDUSTRI AGRO (019.02)
  // =========================================================================
  {
    'unit eselon1': 'Ditjen Industri Agro',
    'unit eselon2': 'Direktorat Hasil Hutan dan Perkebunan',
    satker: 'Ditjen Industri Agro',
    type_komponen: 'Non Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Nilai Tambah dan Daya Saing Industri',
    kegiatan: 'Pengembangan Hilirisasi Industri Kelapa Sawit dan Kakao',
    kro: 'KRO.002 Fasilitasi Industri Hijau',
    ro: 'RO.02 Verifikasi Industri Hijau',
    propinsi: 'Sumatera Utara',
    kabupaten: 'Kab. Deli Serdang',
    'lokasi ro': 'BBSPJI Medan',
    komponen: '063 Bimbingan Teknis Standar Industri Hijau Sektor Kelapa Sawit & Oleokimia',
    alokasi_komponen_0: 640000000,
    target_komponen_0: 45,
    satuan: 'Pabrik Kelapa Sawit',
    tahun_anggaran: '2026',
    kode_anggaran: '019.02.EC.2158.BMA.002.063'
  },
  {
    'unit eselon1': 'Ditjen Industri Agro',
    'unit eselon2': 'Direktorat Minuman, Hasil Tembakau dan Bahan Penyegar',
    satker: 'Ditjen Industri Agro',
    type_komponen: 'Non Operasional',
    sumber_dana: 'PNBP',
    program: 'Program Nilai Tambah dan Daya Saing Industri',
    kegiatan: 'Peningkatan Daya Saing Industri Makanan dan Minuman',
    kro: 'KRO.001 Pembinaan Standar Industri',
    ro: 'RO.01 Perumusan SNI Baru',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Selatan',
    'lokasi ro': 'Kantor Pusat Kemenperin',
    komponen: '070 Fasilitasi Penjaminan Keamanan Pangan & Hazard Analysis (HACCP)',
    alokasi_komponen_0: 890000000,
    target_komponen_0: 50,
    satuan: 'Industri Mamin',
    tahun_anggaran: '2026',
    kode_anggaran: '019.02.EC.2158.BMA.001.070'
  },

  // =========================================================================
  // 6. DITJEN KETAHANAN, PERWILAYAHAN DAN AKSES INDUSTRI INTERNASIONAL (019.06)
  // =========================================================================
  {
    'unit eselon1': 'Ditjen Ketahanan, Perwilayahan dan Akses Industri Internasional',
    'unit eselon2': 'Direktorat Perwilayahan Industri',
    satker: 'Ditjen KPAII',
    type_komponen: 'Non Operasional',
    sumber_dana: 'SBSN',
    program: 'Program Nilai Tambah dan Daya Saing Industri',
    kegiatan: 'Pengembangan Kawasan Industri Ramah Lingkungan (Eco-Industrial Park)',
    kro: 'KRO.002 Fasilitasi Industri Hijau',
    ro: 'RO.04 Audit Energi Pabrik',
    propinsi: 'Bali',
    kabupaten: 'Kota Denpasar',
    'lokasi ro': 'BBSPJI Bali',
    komponen: '060 Pengadaan Mobile Lab Sensor Pemantau Kualitas Udara Kawasan Industri',
    alokasi_komponen_0: 3200000000,
    target_komponen_0: 3,
    satuan: 'Unit Kendaraan Lab',
    tahun_anggaran: '2026',
    kode_anggaran: '019.06.EC.2158.BMA.004.060'
  },
  {
    'unit eselon1': 'Ditjen Ketahanan, Perwilayahan dan Akses Industri Internasional',
    'unit eselon2': 'Direktorat Akses Sumber Daya Industri dan Promosi Internasional',
    satker: 'Ditjen KPAII',
    type_komponen: 'Non Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Nilai Tambah dan Daya Saing Industri',
    kegiatan: 'Promosi Akses Pasar Ekspor Produk Manufaktur Nasional',
    kro: 'KRO.001 Pembinaan Standar Industri',
    ro: 'RO.01 Perumusan SNI Baru',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Selatan',
    'lokasi ro': 'Kantor Pusat Kemenperin',
    komponen: '071 Partisipasi Paviliun Indonesia pada Hannover Messe & Pameran Global',
    alokasi_komponen_0: 4500000000,
    target_komponen_0: 30,
    satuan: 'Delegasi Industri',
    tahun_anggaran: '2026',
    kode_anggaran: '019.06.EC.2158.BMA.001.071'
  },

  // =========================================================================
  // 7. BADAN PENGEMBANGAN SUMBER DAYA MANUSIA INDUSTRI (BPSDMI - 019.08)
  // =========================================================================
  {
    'unit eselon1': 'Badan Pengembangan Sumber Daya Manusia Industri',
    'unit eselon2': 'Pusat Pengembangan Pendidikan Vokasi Industri',
    satker: 'Politeknik STMI Jakarta',
    type_komponen: 'Operasional',
    sumber_dana: 'RM (Rupiah Murni)',
    program: 'Program Pendidikan dan Pelatihan Vokasi',
    kegiatan: 'Penyelenggaraan Pendidikan Tinggi Vokasi Industri',
    kro: 'KRO.004 Layanan Perkantoran',
    ro: 'RO.05 Gaji dan Tunjangan',
    propinsi: 'DKI Jakarta',
    kabupaten: 'Jakarta Pusat',
    'lokasi ro': 'Kampus Politeknik STMI',
    komponen: '001-Gaji dan tunjangan',
    alokasi_komponen_0: 8900000000,
    target_komponen_0: 12,
    satuan: 'Bulan Layanan',
    tahun_anggaran: '2026',
    kode_anggaran: '019.08.GG.2157.EBA.994.001'
  },
  {
    'unit eselon1': 'Badan Pengembangan Sumber Daya Manusia Industri',
    'unit eselon2': 'Pusat Pengembangan Pendidikan Vokasi Industri',
    satker: 'Politeknik STTT Bandung',
    type_komponen: 'Non Operasional',
    sumber_dana: 'SBSN',
    program: 'Program Pendidikan dan Pelatihan Vokasi',
    kegiatan: 'Penguatan Sarana Workshop & Lab Vokasi Industri Tekstil',
    kro: 'KRO.001 Pembinaan Standar Industri',
    ro: 'RO.01 Perumusan SNI Baru',
    propinsi: 'Jawa Barat',
    kabupaten: 'Kota Bandung',
    'lokasi ro': 'Kampus Politeknik STTT Bandung',
    komponen: '072 Pengadaan Mesin Tenun Otomatis & Lab Uji Serat Tekstil Digital',
    alokasi_komponen_0: 3600000000,
    target_komponen_0: 8,
    satuan: 'Paket Mesin Workshop',
    tahun_anggaran: '2026',
    kode_anggaran: '019.08.GG.2156.BMA.001.072'
  }
];
